AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example Rocket Lamb API
Globals:
  Api:
    BinaryMediaTypes:
    - '*/*'
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://lavishweb-rocket-app-bucket/e51c961a8f0f0bf59bd75671e1f776be
      Handler: DUMMY
      Runtime: provided.al2023
      MemorySize: 128
      Events:
        Web:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
        WebRoot:
          Type: Api
          Properties:
            Path: /
            Method: ANY
Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
